id: P70FCD378
initial_creation_type: input
source_metadata:
  Title: Adhyātmasāraśatakam(saṭīkam)
  Editor: Śrīprabhākaragupta
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  अध्यात्मसारशतकम् (सटीकम्):
    Text Version: Devanagari
    Input Personnel: Anjana Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:13:42.460770'
last_modified_at: '2022-03-08T17:13:42.460778'
